default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  template: template0
  username: ubuntu
  password: ''

development:
  <<: *default
  database: api-challenge-dinosys_development

test:
  <<: *default
  database: api-challenge-dinosys_test

production:
  <<: *default
  database: api-challenge-dinosys_production
  username: api-challenge-dinosys
  password: <%= ENV['API-CHALLENGE-DINOSYS_DATABASE_PASSWORD'] %>
